In [6]:
import numpy as np
from sklearn.linear_model import LinearRegression

#The class sklearn.linear_model.LinearRegression will be used to perform linear and polynomial regression and make predictions accordingly.




In [17]:
x = np.array([5, 10, 29, 35, 45, 55]).reshape((-1, 1))
x

array([[ 5],
       [10],
       [29],
       [35],
       [45],
       [55]])

In [18]:
y = np.array([10, 19, 59, 69, 91, 108])

In [19]:
y

array([ 10,  19,  59,  69,  91, 108])

In [20]:
model = LinearRegression()


In [21]:
model.fit(x, y)


LinearRegression()

In [22]:
r_sq = model.score(x, y)

In [23]:
r_sq

0.999057329972338

In [24]:
print('intercept:', model.intercept_)

intercept: 0.001490574309535475


In [25]:
y_pred = model.predict(x)

In [26]:
y_pred

array([  9.94537484,  19.8892591 ,  57.67601929,  69.6086804 ,
        89.49644893, 109.38421745])